### DISCUSSION TITLE
Service file format

### DISCUSSION THREAD

**Discussion by softexpert** [davmac314/dinit#389] [Ideas]
Hello,

Simple question for a complex topic: since the number of parameters and their options are increasing, the service description files will become more complex and will look less intelligible.
Some options have very specific syntax, meaning that there are less chances to find out there syntactic highlighters, analyzers, validators and so on.

Could it be a good idea to switch to TOML 1.0 format instead ?

There is a parser ([tomlc99](https://github.com/cktan/tomlc99), written in C99 and TOML 1.0 compliant), under MIT license, that can help with the low level parsing.

The service file could look similar to this:

```TOML
[dinit]
name = "my_process"
description = "this is my example process"
version = "1.2.3"
enabled = true
# [ "process", "bgprocess", "scripted", "internal", "triggered" ]
type = "process"

[dinit.depends]
depends-on = [ "network.target" ]
depends-ms = [ "aaa" ]
waits-for = [ "ccc" ]
after = ""
before = ""
chain-to = ""

[dinit.depends.d]
depends-on = ["", "", ""]

[dinit.depends.ms]
depends-ms = ["", "", ""]

[dinit.depends.waits]
waits-for = ["", "", ""]

[dinit.process]
command = "`id -user`\\$environment_variable\\$[local-variable1]\\${system_variable}"
command-extra = 'a\b'
stop-command = ""
stop-command-extra = ""
working-dir = ""
pid-file = ""
# {none | signal-name}
term-signal = "none"
# {pipefd:fd-number | pipevar:env-var-name}
ready-notification = 'pipefd:5'

[dinit.process.socket]
socket-listen = "path"
socket-permission = 600
socket-uid = "1000"
socket-gid = "user"

[dinit.process.scheduling]
# ["yes", "true", "on-failure", "no", "false"]
restart = true
# smooth-recovery ["true", "false", "yes", "no"]
smooth-recovery = false
restart-delay = 1.2
restart-limit-interval = 123.45
restart-limit-count = 5
start-timeout = 30
stop-timeout = 30

[dinit.process.identity]
# identity
run-as = ""

[dinit.process.logging]
# {file | buffer | pipe | none}
log-type = "buffer"
logfile = "log-file-path"
logfile-permissions = 644
#{numeric-user-id | username}
logfile-uid = "1000"
# {numeric-group-id | group-name}
logfile-gid = "users"
log-buffer-size = 65535


[dinit.environment]
env-file = [""]

[dinit.environment.variables]
local-variable1="`id -user`"

[dinit.options]

```
Thank you for the great work already done, I'm really enjoying the serenity that comes with dinit !
